### ISSUE TITLE
Update for R 3.4.0

### ISSUE THREAD

**Issue by roryk** [conda-forge/r-assertive.files-feedstock#3]
Need someone with the power to: @conda-forge-admin, please rerender for me. Thanks!

**Comment by roryk** [comment]
@conda-forge-admin, please rerender

**Comment by bgruening** [comment]
3.4 packages are available, right? https://anaconda.org/conda-forge/r-assertive.files/files

**Comment by bgruening** [comment]
@roryk please let me know if I have missed anything?
